config/routes.rb
Rails.application.routes.draw do
  get "sitemap.xml" => "sitemaps#index", :format => "xml", :as => :sitemap

  get 'likes/create'

  get 'likes/destroy'

  resources :people, only: [:create, :destroy, :show, :edit]
  root :to => 'pages#home'

  resources :surveys
  resources :attempts

  resources :genres

  resources :movies

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
 
  resources :users, :only => [:show, :index] do
    member do
      get :following, :followers
    end
  end

  resources :followships, only: [:create, :destroy]
  resources :likes, only: [:create, :destroy]
  
  resources :notifications, only: [:index, :destroy] do
    collection do
      post :clear
    end
  end

  resources :search_results, only: [:index]

end

app/models/notification.rb
class Notification < ActiveRecord::Base
  belongs_to :user
  belongs_to :movie
  default_scope -> { order(created_at: :desc)}

  scope :unread, ->{where(read: false)}



  after_create :real_time_push_to_client

  def real_time_push_to_client
  	if self.user
  		hash = {}
  		hash[:count] = self.user.notifications.unread.count
        MessageBus.publish "/notifications_count/#{self.user.temp_access_token}", hash
  	end
  end
end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
  def index
    @notifications = current_user.notifications.unread
    # debugger
  end

  def destroy
    @notification = current_user.notifications.find(params[:id])
    @notification.destroy
    redirect_to notifications_path 
  end

  def clear
    current_user.notifications.delete_all
    flash[:success] = "All notifications deleted."
    redirect_to root_url
  end


end

app/helpers/notifications_helper.rb
module NotificationsHelper
end

app/views/notifications/_notification.html.erb
<li class="media">
  <div class="media-left">
    <%= link_to gravatar_for(User.find(notification.followed_id)), User.find(notification.followed_id)  %>  
  </div>
  <div class="media-body">
    Your friend <%= User.find(notification.followed_id).name %> liked  <%= link_to notification.movie.title, notification.movie %>
    <% if !notification.read? %>
      <span class="new label label-warning">new</span>
    <% end %>
    <span class="timestamp pull-right">
    	<%= time_ago_in_words(notification.created_at) %>
    </span>
  </div>
</li>

app/views/notifications/index.html.erb
<div class="row">
  <div class="col-md-8 col-md-offset-2">
    <div id="notifications" class="panel panel-default">
      <div class="panel-heading">
        <span class="pull-right">
          <%= link_to "delete", clear_notifications_path, class: "btn btn-danger", method: :post  %>
        </span>
        <h4>Notifications</h4>
      </div>
      <% if @notifications.blank? %>
        <div class="no-result panel-body">Currently, there are no notifications</div>
      <% else %>
      <div class="panel-body">
        <ul class="media-list"> 
          <%= render partial: "notification", collection: @notifications %>
        </ul>
      </div>
     <% end %>
    </div>
  </div>
</div>