config/routes.rb
Rails.application.routes.draw do
  get "sitemap.xml" => "sitemaps#index", :format => "xml", :as => :sitemap

  get 'likes/create'

  get 'likes/destroy'

  resources :people, only: [:create, :destroy, :show, :edit]
  root :to => 'pages#home'

  resources :surveys
  resources :attempts

  resources :genres

  resources :movies

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
 
  resources :users, :only => [:show, :index] do
    member do
      get :following, :followers
    end
  end

  resources :followships, only: [:create, :destroy]
  resources :likes, only: [:create, :destroy]
  
  resources :notifications, only: [:index, :destroy] do
    collection do
      post :clear
    end
  end

  resources :search_results, only: [:index]

end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Movie Radar", root_path, class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <%= form_for :search_results, url: :search_results, method: :get, html:{class: "navbar-form navbar-left"} do |f| %>
            <span class="glyphicon glyphicon-search" aria-hidden="true"></span>
            <%= text_field_tag :keywords, nil,
                       placeholder: "Search", class: "form-control" %> 
            <%= submit_tag "Submit", class: "btn btn-primary" %>
        <% end %>
      <ul class="nav navbar-nav navbar-right">
        <li>
          <%= link_to genres_path do %>
            <span class="glyphicon glyphicon-film"></span> Movies
          <% end %>
        </li>
        <li>
          <%= link_to users_path  do %>
            <span class="glyphicon glyphicon-user"></span> User
          <% end %>
        </li>
        <% if user_signed_in? %>
          <%
            badge_class = ""
            badge_class = "new" if current_user.notifications.unread.count > 0
          %> 
          <li>
            <%= link_to surveys_path do %>
              <span class="glyphicon glyphicon-pencil"></span> Quiz
            <% end %>
          </li>
          <li class="notification-count">
            <a href="<%= notifications_path %>" class=<%= badge_class %> > 
              <span class="glyphicon glyphicon-bell"></span>Notifications 
              <span class="count"><%= current_user.notifications.unread.count %></span>
            </a>
          </li> 
          <li>
            <%= link_to edit_user_registration_path do %>
              <span class="glyphicon glyphicon-cog"></span> Account Settings
            <% end %>
          </li>
          <li>
            <%= link_to destroy_user_session_path, method: :delete do %>
            <span class="glyphicon glyphicon-log-out"></span> Log out
            <% end %>
          </li>
        <% else %>
          <li>
            <%= link_to new_user_session_path do %>
            <span class="glyphicon glyphicon-log-in"></span> Sign in
            <% end %>
          </li>
        <% end %>

      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta name="msvalidate.01" content="0FACECC10CB18B7A0AB0BB640588692E" />
  <title>Project</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => false %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => false %>
  <script type="text/javascript" data-turbolinks-eval=false>
    <% if current_user %>
      App.current_user_id = <%= current_user.id %>;
      App.access_token = "<%= current_user.temp_access_token %>";
    <% end %>
  </script>
  <%= csrf_meta_tags %>
</head>
<body>
	<%= render "layouts/header" %>

  	<div class="container-fluid">
	<% flash.each do |key, value| %>
	  <div class="alert alert-<%= key %>">
	    <a href="#" data-dismiss="alert" class="close">×</a>
	      <ul>
	        <li>
	          <%= value %>
	        </li>
	      </ul>
	  </div>
	<% end %>
		<%= yield %>
	</div>
</body>
</html>